# MoveIt uses this configuration for controller management

trajectory_execution:
  allowed_execution_duration_scaling: 1.2
  allowed_goal_duration_margin: 0.5
  allowed_start_tolerance: 0.01
  execution_duration_monitoring: false

controller_names:
    - rebel_arm_trajectory_controller
    - igus_gripper_controller

rebel_arm_trajectory_controller:
  type: FollowJointTrajectory
  action_ns: follow_joint_trajectory
  default: true
  joints:
    - joint1
    - joint2
    - joint3
    - joint4
    - joint5
    - joint6
igus_gripper_controller:
  type: GripperCommand
  joints:
    - gripper_l_joint
    - gripper_r_joint
  action_ns: gripper_cmd
  default: true