controller_manager:
  ros__parameters:
    update_rate: 200 # Hz, higher is better for servo

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    rebel_arm_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    rebel_arm_position_controller:
      type: position_controllers/JointGroupPositionController

rebel_arm_trajectory_controller:
  ros__parameters:
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
    command_interfaces: [position]
    state_interfaces: [position, velocity]

rebel_arm_position_controller:
  ros__parameters:
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
    command_interfaces: [position]
    state_interfaces: [position, velocity]


